/** Editorial PointFFC aliases, keyed only by football-data team externalId.
 * One entry per club, including clubs shared by domestic leagues and CL.
 * Coverage inventory and provenance: docs/futebol-nomes-clubes.md.
 */
export const NOMES_CLUBES_INTERNACIONAIS: Readonly<Record<number, Readonly<{ nome: string; nomeCurto: string }>>> = Object.freeze({
  1: { nome: 'Colônia', nomeCurto: 'Colônia' },
  2: { nome: 'Hoffenheim', nomeCurto: 'Hoffenheim' },
  3: { nome: 'Bayer Leverkusen', nomeCurto: 'Leverkusen' },
  4: { nome: 'Borussia Dortmund', nomeCurto: 'Dortmund' },
  5: { nome: 'Bayern de Munique', nomeCurto: 'Bayern' },
  6: { nome: 'Schalke 04', nomeCurto: 'Schalke' },
  7: { nome: 'Hamburgo', nomeCurto: 'Hamburgo' },
  10: { nome: 'Stuttgart', nomeCurto: 'Stuttgart' },
  12: { nome: 'Werder Bremen', nomeCurto: 'Werder Bremen' },
  15: { nome: 'Mainz 05', nomeCurto: 'Mainz' },
  16: { nome: 'Augsburg', nomeCurto: 'Augsburg' },
  17: { nome: 'Freiburg', nomeCurto: 'Freiburg' },
  18: { nome: 'Borussia Mönchengladbach', nomeCurto: 'Mönchengladbach' },
  19: { nome: 'Eintracht Frankfurt', nomeCurto: 'Frankfurt' },
  28: { nome: 'Union Berlin', nomeCurto: 'Union Berlin' },
  29: { nome: 'Paderborn', nomeCurto: 'Paderborn' },
  57: { nome: 'Arsenal', nomeCurto: 'Arsenal' },
  58: { nome: 'Aston Villa', nomeCurto: 'Aston Villa' },
  59: { nome: 'Blackburn Rovers', nomeCurto: 'Blackburn' },
  60: { nome: 'Bolton Wanderers', nomeCurto: 'Bolton' },
  61: { nome: 'Chelsea', nomeCurto: 'Chelsea' },
  62: { nome: 'Everton', nomeCurto: 'Everton' },
  63: { nome: 'Fulham', nomeCurto: 'Fulham' },
  64: { nome: 'Liverpool', nomeCurto: 'Liverpool' },
  65: { nome: 'Manchester City', nomeCurto: 'Manchester City' },
  66: { nome: 'Manchester United', nomeCurto: 'Manchester United' },
  67: { nome: 'Newcastle United', nomeCurto: 'Newcastle' },
  68: { nome: 'Norwich City', nomeCurto: 'Norwich' },
  69: { nome: 'Queens Park Rangers', nomeCurto: 'QPR' },
  70: { nome: 'Stoke City', nomeCurto: 'Stoke' },
  71: { nome: 'Sunderland', nomeCurto: 'Sunderland' },
  72: { nome: 'Swansea City', nomeCurto: 'Swansea' },
  73: { nome: 'Tottenham', nomeCurto: 'Tottenham' },
  74: { nome: 'West Bromwich Albion', nomeCurto: 'West Bromwich' },
  76: { nome: 'Wolverhampton', nomeCurto: 'Wolves' },
  77: { nome: 'Athletic Bilbao', nomeCurto: 'Athletic Bilbao' },
  78: { nome: 'Atlético de Madrid', nomeCurto: 'Atlético' },
  79: { nome: 'Osasuna', nomeCurto: 'Osasuna' },
  80: { nome: 'Espanyol', nomeCurto: 'Espanyol' },
  81: { nome: 'Barcelona', nomeCurto: 'Barcelona' },
  82: { nome: 'Getafe', nomeCurto: 'Getafe' },
  84: { nome: 'Málaga', nomeCurto: 'Málaga' },
  86: { nome: 'Real Madrid', nomeCurto: 'Real Madrid' },
  87: { nome: 'Rayo Vallecano', nomeCurto: 'Rayo Vallecano' },
  88: { nome: 'Levante', nomeCurto: 'Levante' },
  90: { nome: 'Real Betis', nomeCurto: 'Betis' },
  92: { nome: 'Real Sociedad', nomeCurto: 'Real Sociedad' },
  94: { nome: 'Villarreal', nomeCurto: 'Villarreal' },
  95: { nome: 'Valencia', nomeCurto: 'Valencia' },
  98: { nome: 'Milan', nomeCurto: 'Milan' },
  99: { nome: 'Fiorentina', nomeCurto: 'Fiorentina' },
  100: { nome: 'Roma', nomeCurto: 'Roma' },
  102: { nome: 'Atalanta', nomeCurto: 'Atalanta' },
  103: { nome: 'Bologna', nomeCurto: 'Bologna' },
  104: { nome: 'Cagliari', nomeCurto: 'Cagliari' },
  107: { nome: 'Genoa', nomeCurto: 'Genoa' },
  108: { nome: 'Inter de Milão', nomeCurto: 'Inter' },
  109: { nome: 'Juventus', nomeCurto: 'Juventus' },
  110: { nome: 'Lazio', nomeCurto: 'Lazio' },
  112: { nome: 'Parma', nomeCurto: 'Parma' },
  113: { nome: 'Napoli', nomeCurto: 'Napoli' },
  115: { nome: 'Udinese', nomeCurto: 'Udinese' },
  263: { nome: 'Alavés', nomeCurto: 'Alavés' },
  285: { nome: 'Elche', nomeCurto: 'Elche' },
  322: { nome: 'Hull City', nomeCurto: 'Hull City' },
  325: { nome: 'Portsmouth', nomeCurto: 'Portsmouth' },
  328: { nome: 'Burnley', nomeCurto: 'Burnley' },
  332: { nome: 'Birmingham City', nomeCurto: 'Birmingham' },
  340: { nome: 'Southampton', nomeCurto: 'Southampton' },
  341: { nome: 'Leeds United', nomeCurto: 'Leeds United' },
  342: { nome: 'Derby County', nomeCurto: 'Derby County' },
  343: { nome: 'Middlesbrough', nomeCurto: 'Middlesbrough' },
  346: { nome: 'Watford', nomeCurto: 'Watford' },
  348: { nome: 'Charlton Athletic', nomeCurto: 'Charlton' },
  349: { nome: 'Ipswich Town', nomeCurto: 'Ipswich Town' },
  351: { nome: 'Nottingham Forest', nomeCurto: 'Nottingham Forest' },
  354: { nome: 'Crystal Palace', nomeCurto: 'Crystal Palace' },
  356: { nome: 'Sheffield United', nomeCurto: 'Sheffield United' },
  384: { nome: 'Millwall', nomeCurto: 'Millwall' },
  387: { nome: 'Bristol City', nomeCurto: 'Bristol City' },
  397: { nome: 'Brighton', nomeCurto: 'Brighton' },
  402: { nome: 'Brentford', nomeCurto: 'Brentford' },
  404: { nome: 'Wrexham', nomeCurto: 'Wrexham' },
  454: { nome: 'Venezia', nomeCurto: 'Venezia' },
  470: { nome: 'Frosinone', nomeCurto: 'Frosinone' },
  471: { nome: 'Sassuolo', nomeCurto: 'Sassuolo' },
  496: { nome: 'Rio Ave', nomeCurto: 'Rio Ave' },
  498: { nome: 'Sporting', nomeCurto: 'Sporting' },
  503: { nome: 'Porto', nomeCurto: 'Porto' },
  511: { nome: 'Toulouse', nomeCurto: 'Toulouse' },
  512: { nome: 'Brest', nomeCurto: 'Brest' },
  516: { nome: 'Olympique de Marseille', nomeCurto: 'Marseille' },
  519: { nome: 'Auxerre', nomeCurto: 'Auxerre' },
  521: { nome: 'Lille', nomeCurto: 'Lille' },
  522: { nome: 'Nice', nomeCurto: 'Nice' },
  523: { nome: 'Lyon', nomeCurto: 'Lyon' },
  524: { nome: 'Paris Saint-Germain', nomeCurto: 'PSG' },
  525: { nome: 'Lorient', nomeCurto: 'Lorient' },
  529: { nome: 'Rennes', nomeCurto: 'Rennes' },
  531: { nome: 'Troyes', nomeCurto: 'Troyes' },
  532: { nome: 'Angers', nomeCurto: 'Angers' },
  533: { nome: 'Le Havre', nomeCurto: 'Le Havre' },
  535: { nome: 'Le Mans', nomeCurto: 'Le Mans' },
  546: { nome: 'Lens', nomeCurto: 'Lens' },
  548: { nome: 'Monaco', nomeCurto: 'Monaco' },
  558: { nome: 'Celta de Vigo', nomeCurto: 'Celta' },
  559: { nome: 'Sevilla', nomeCurto: 'Sevilla' },
  560: { nome: 'Deportivo La Coruña', nomeCurto: 'Deportivo' },
  563: { nome: 'West Ham', nomeCurto: 'West Ham' },
  576: { nome: 'Strasbourg', nomeCurto: 'Strasbourg' },
  582: { nome: 'Estoril', nomeCurto: 'Estoril' },
  583: { nome: 'Moreirense', nomeCurto: 'Moreirense' },
  586: { nome: 'Torino', nomeCurto: 'Torino' },
  610: { nome: 'Galatasaray', nomeCurto: 'Galatasaray' },
  613: { nome: 'Fenerbahçe', nomeCurto: 'Fenerbahçe' },
  666: { nome: 'Twente', nomeCurto: 'Twente' },
  670: { nome: 'Excelsior', nomeCurto: 'Excelsior' },
  672: { nome: 'Willem II', nomeCurto: 'Willem II' },
  673: { nome: 'Heerenveen', nomeCurto: 'Heerenveen' },
  674: { nome: 'PSV Eindhoven', nomeCurto: 'PSV' },
  675: { nome: 'Feyenoord', nomeCurto: 'Feyenoord' },
  676: { nome: 'Utrecht', nomeCurto: 'Utrecht' },
  677: { nome: 'Groningen', nomeCurto: 'Groningen' },
  678: { nome: 'Ajax', nomeCurto: 'Ajax' },
  680: { nome: 'ADO Den Haag', nomeCurto: 'ADO Den Haag' },
  682: { nome: 'AZ Alkmaar', nomeCurto: 'AZ' },
  684: { nome: 'PEC Zwolle', nomeCurto: 'Zwolle' },
  712: { nome: 'Arouca', nomeCurto: 'Arouca' },
  715: { nome: 'Cardiff City', nomeCurto: 'Cardiff' },
  718: { nome: 'Go Ahead Eagles', nomeCurto: 'Go Ahead Eagles' },
  719: { nome: 'Elversberg', nomeCurto: 'Elversberg' },
  721: { nome: 'RB Leipzig', nomeCurto: 'RB Leipzig' },
  851: { nome: 'Club Brugge', nomeCurto: 'Brugge' },
  930: { nome: 'Slavia Praga', nomeCurto: 'Slavia' },
  1044: { nome: 'Bournemouth', nomeCurto: 'Bournemouth' },
  1045: { nome: 'Paris FC', nomeCurto: 'Paris FC' },
  1076: { nome: 'Coventry City', nomeCurto: 'Coventry' },
  1081: { nome: 'Preston North End', nomeCurto: 'Preston' },
  1126: { nome: 'Lincoln City', nomeCurto: 'Lincoln City' },
  1887: { nome: 'Shakhtar Donetsk', nomeCurto: 'Shakhtar' },
  1899: { nome: 'AEK Atenas', nomeCurto: 'AEK' },
  1903: { nome: 'Benfica', nomeCurto: 'Benfica' },
  1909: { nome: 'Cambuur', nomeCurto: 'Cambuur' },
  1912: { nome: 'Telstar', nomeCurto: 'Telstar' },
  1915: { nome: 'NEC Nijmegen', nomeCurto: 'NEC' },
  1920: { nome: 'Fortuna Sittard', nomeCurto: 'Fortuna Sittard' },
  2016: { nome: 'LASK Linz', nomeCurto: 'LASK' },
  5335: { nome: 'Racing Santander', nomeCurto: 'Racing Santander' },
  5527: { nome: 'Académico de Viseu', nomeCurto: 'Acad. Viseu' },
  5529: { nome: 'Nacional da Madeira', nomeCurto: 'Nacional' },
  5530: { nome: 'Santa Clara', nomeCurto: 'Santa Clara' },
  5531: { nome: 'Famalicão', nomeCurto: 'Famalicão' },
  5533: { nome: 'Gil Vicente', nomeCurto: 'Gil Vicente' },
  5543: { nome: 'Vitória de Guimarães', nomeCurto: 'Vitória SC' },
  5575: { nome: 'Marítimo', nomeCurto: 'Marítimo' },
  5613: { nome: 'Braga', nomeCurto: 'Braga' },
  5720: { nome: 'Viking', nomeCurto: 'Viking' },
  5721: { nome: 'Bodø/Glimt', nomeCurto: 'Bodø/Glimt' },
  5890: { nome: 'Lecce', nomeCurto: 'Lecce' },
  5911: { nome: 'Monza', nomeCurto: 'Monza' },
  6618: { nome: 'Casa Pia', nomeCurto: 'Casa Pia' },
  6806: { nome: 'Sparta Rotterdam', nomeCurto: 'Sparta Rotterdam' },
  7397: { nome: 'Como', nomeCurto: 'Como' },
  7509: { nome: 'Slovan Bratislava', nomeCurto: 'Slovan' },
  7822: { nome: 'Alverca', nomeCurto: 'Alverca' },
  9136: { nome: 'Estrela da Amadora', nomeCurto: 'Estrela Amadora' },
  10233: { nome: 'Sabah', nomeCurto: 'Sabah' },
});
