CREATE TABLE `CARTEIRA` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuarioId` INTEGER UNSIGNED NOT NULL,
  `saldoDisponivel` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `saldoBloqueado` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `status` ENUM('ATIVA', 'BLOQUEADA') NOT NULL DEFAULT 'ATIVA',
  `criadoEm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `atualizadoEm` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `CARTEIRA_usuarioId_key` (`usuarioId`),
  CONSTRAINT `CARTEIRA_usuarioId_fkey` FOREIGN KEY (`usuarioId`) REFERENCES `USUARIO` (`id_usuario`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `MOVIMENTACAO_CARTEIRA` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `carteiraId` INTEGER UNSIGNED NOT NULL,
  `tipo` ENUM('CREDITO', 'DEBITO') NOT NULL,
  `origem` ENUM('RECARGA_PIX', 'INSCRICAO', 'ESTORNO', 'AJUSTE') NOT NULL,
  `valor` DECIMAL(12,2) NOT NULL,
  `saldoAnterior` DECIMAL(12,2) NOT NULL,
  `saldoPosterior` DECIMAL(12,2) NOT NULL,
  `referenciaId` VARCHAR(255) NULL,
  `descricao` TEXT NULL,
  `status` ENUM('CONFIRMADA') NOT NULL DEFAULT 'CONFIRMADA',
  `criadoEm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `MOVIMENTACAO_CARTEIRA_carteiraId_criadoEm_id_idx` (`carteiraId`, `criadoEm`, `id`),
  CONSTRAINT `MOVIMENTACAO_CARTEIRA_carteiraId_fkey` FOREIGN KEY (`carteiraId`) REFERENCES `CARTEIRA` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
