CREATE TABLE `TIME_CARTOLA` (
    `TIME_ID` INTEGER UNSIGNED NOT NULL,
    `NOME_TIME` VARCHAR(255) NOT NULL,
    `NOME_CARTOLEIRO` VARCHAR(255) NULL,
    `SLUG` VARCHAR(255) NULL,
    `ESCUDO_URL` TEXT NULL,
    `FOTO_PERFIL_URL` TEXT NULL,
    `ASSINANTE` BOOLEAN NULL,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    PRIMARY KEY (`TIME_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `TIME_RODADA` (
    `ID` VARCHAR(36) NOT NULL,
    `TIME_ID` INTEGER UNSIGNED NOT NULL,
    `TEMPORADA` SMALLINT UNSIGNED NOT NULL,
    `RODADA` TINYINT UNSIGNED NOT NULL,
    `ESQUEMA_TATICO` INTEGER UNSIGNED NULL,
    `PATRIMONIO` DECIMAL(12, 2) NULL,
    `CAPITAO_ID` INTEGER UNSIGNED NULL,
    `STATUS` ENUM('CAPTURADO') NOT NULL DEFAULT 'CAPTURADO',
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    UNIQUE INDEX `TIME_RODADA_TIME_ID_TEMPORADA_RODADA_key` (`TIME_ID`, `TEMPORADA`, `RODADA`),
    INDEX `TIME_RODADA_TEMPORADA_RODADA_idx` (`TEMPORADA`, `RODADA`),
    PRIMARY KEY (`ID`),
    CONSTRAINT `TIME_RODADA_TIME_ID_fkey`
      FOREIGN KEY (`TIME_ID`) REFERENCES `TIME_CARTOLA`(`TIME_ID`)
      ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ESCALACAO_TIME_RODADA` (
    `ID` VARCHAR(36) NOT NULL,
    `TIME_RODADA_ID` VARCHAR(36) NOT NULL,
    `ATLETA_ID` INTEGER UNSIGNED NOT NULL,
    `POSICAO_ID` INTEGER UNSIGNED NOT NULL,
    `CLUBE_ID` INTEGER UNSIGNED NULL,
    `TITULAR` BOOLEAN NOT NULL,
    `RESERVA` BOOLEAN NOT NULL,
    `CAPITAO` BOOLEAN NOT NULL,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ESCALACAO_TIME_RODADA_TIME_RODADA_ID_ATLETA_ID_key` (`TIME_RODADA_ID`, `ATLETA_ID`),
    INDEX `ESCALACAO_TIME_RODADA_ATLETA_ID_idx` (`ATLETA_ID`),
    PRIMARY KEY (`ID`),
    CONSTRAINT `ESCALACAO_TIME_RODADA_TIME_RODADA_ID_fkey`
      FOREIGN KEY (`TIME_RODADA_ID`) REFERENCES `TIME_RODADA`(`ID`)
      ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
