SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `SUBSTITUICAO_TIME_RODADA`;
DROP TABLE IF EXISTS `PONTUACAO_TIME_RODADA`;
DROP TABLE IF EXISTS `ESCALACAO_TIME_RODADA`;
DROP TABLE IF EXISTS `TIME_RODADA`;
DROP TABLE IF EXISTS `TIME_CARTOLA`;
DROP TABLE IF EXISTS `TIME_USUARIO`;
DROP TABLE IF EXISTS `PASSWORD_RESET_TOKEN`;
DROP TABLE IF EXISTS `AUTH_ACCOUNT`;
DROP TABLE IF EXISTS `USUARIO`;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `USUARIO` (
    `id_usuario` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `firebase_uid` VARCHAR(128) NULL,
    `senha_hash` VARCHAR(255) NULL,
    `nome` VARCHAR(255) NULL,
    `email` VARCHAR(255) NOT NULL,
    `foto_url` TEXT NULL,
    `tipo_usuario` ENUM('PLAYER', 'ORGANIZER', 'PLATFORM_ADMIN') NOT NULL DEFAULT 'PLAYER',
    `status` ENUM('ATIVO', 'INATIVO', 'BLOQUEADO') NOT NULL DEFAULT 'ATIVO',
    `data_criacao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `data_atualizacao` DATETIME(3) NOT NULL,
    UNIQUE INDEX `USUARIO_firebase_uid_key`(`firebase_uid`),
    UNIQUE INDEX `USUARIO_email_key`(`email`),
    PRIMARY KEY (`id_usuario`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `TIME_USUARIO` (
    `USUARIO_ID` INTEGER UNSIGNED NOT NULL,
    `TIME_ID` INTEGER UNSIGNED NOT NULL,
    `NOME` VARCHAR(255) NOT NULL,
    `NOME_CARTOLA` VARCHAR(255) NULL,
    `SLUG` VARCHAR(255) NULL,
    `URL_ESCUDO_PNG` TEXT NULL,
    `FOTO_PERFIL` TEXT NULL,
    `ASSINANTE` BOOLEAN NULL,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,
    INDEX `TIME_USUARIO_TIME_ID_idx`(`TIME_ID`),
    PRIMARY KEY (`USUARIO_ID`, `TIME_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `TIME_CARTOLA` (
    `TIME_ID` INTEGER UNSIGNED NOT NULL,
    `NOME_TIME` VARCHAR(255) NOT NULL,
    `NOME_CARTOLEIRO` VARCHAR(255) NULL,
    `SLUG` VARCHAR(255) NULL,
    `ESCUDO_URL` TEXT NULL,
    `FOTO_PERFIL_URL` TEXT NULL,
    `ASSINANTE` BOOLEAN NULL,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,
    PRIMARY KEY (`TIME_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `TIME_RODADA` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `TIME_ID` INTEGER UNSIGNED NOT NULL,
    `TEMPORADA` SMALLINT UNSIGNED NOT NULL,
    `RODADA` TINYINT UNSIGNED NOT NULL,
    `ESQUEMA_TATICO` INTEGER UNSIGNED NULL,
    `PATRIMONIO` DECIMAL(12, 2) NULL,
    `CAPITAO_ID` INTEGER UNSIGNED NULL,
    `RESERVA_LUXO_ID` INTEGER UNSIGNED NULL,
    `STATUS` ENUM('CAPTURADO') NOT NULL DEFAULT 'CAPTURADO',
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,
    INDEX `TIME_RODADA_TEMPORADA_RODADA_idx`(`TEMPORADA`, `RODADA`),
    UNIQUE INDEX `TIME_RODADA_TIME_ID_TEMPORADA_RODADA_key`(`TIME_ID`, `TEMPORADA`, `RODADA`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SUBSTITUICAO_TIME_RODADA` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `TIME_RODADA_ID` INTEGER UNSIGNED NOT NULL,
    `ATLETA_SAIU_ID` INTEGER UNSIGNED NOT NULL,
    `ATLETA_ENTROU_ID` INTEGER UNSIGNED NOT NULL,
    `POSICAO_ID` INTEGER UNSIGNED NOT NULL,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,
    INDEX `SUBSTITUICAO_TIME_RODADA_ATLETA_SAIU_ID_idx`(`ATLETA_SAIU_ID`),
    INDEX `SUBSTITUICAO_TIME_RODADA_ATLETA_ENTROU_ID_idx`(`ATLETA_ENTROU_ID`),
    UNIQUE INDEX `SUB_TR_PAIR_key`(`TIME_RODADA_ID`, `ATLETA_SAIU_ID`, `ATLETA_ENTROU_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `PONTUACAO_TIME_RODADA` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `TIME_RODADA_ID` INTEGER UNSIGNED NOT NULL,
    `PONTUACAO` DECIMAL(12, 2) NOT NULL,
    `STATUS` ENUM('PARCIAL', 'FINAL') NOT NULL DEFAULT 'PARCIAL',
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,
    UNIQUE INDEX `PONTUACAO_TIME_RODADA_TIME_RODADA_ID_key`(`TIME_RODADA_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ESCALACAO_TIME_RODADA` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `TIME_RODADA_ID` INTEGER UNSIGNED NOT NULL,
    `ATLETA_ID` INTEGER UNSIGNED NOT NULL,
    `POSICAO_ID` INTEGER UNSIGNED NOT NULL,
    `CLUBE_ID` INTEGER UNSIGNED NULL,
    `TITULAR` BOOLEAN NOT NULL,
    `RESERVA` BOOLEAN NOT NULL,
    `CAPITAO` BOOLEAN NOT NULL,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,
    INDEX `ESCALACAO_TIME_RODADA_ATLETA_ID_idx`(`ATLETA_ID`),
    UNIQUE INDEX `ESCALACAO_TIME_RODADA_TIME_RODADA_ID_ATLETA_ID_key`(`TIME_RODADA_ID`, `ATLETA_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `AUTH_ACCOUNT` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` INTEGER UNSIGNED NOT NULL,
    `provider` ENUM('GOOGLE', 'APPLE') NOT NULL,
    `provider_account_id` VARCHAR(255) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    UNIQUE INDEX `AUTH_ACCOUNT_provider_provider_account_id_key`(`provider`, `provider_account_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `PASSWORD_RESET_TOKEN` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` INTEGER UNSIGNED NOT NULL,
    `token_hash` CHAR(64) NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `used_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE INDEX `PASSWORD_RESET_TOKEN_token_hash_key`(`token_hash`),
    INDEX `PASSWORD_RESET_TOKEN_user_id_idx`(`user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `TIME_USUARIO` ADD CONSTRAINT `TIME_USUARIO_USUARIO_ID_fkey` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO`(`id_usuario`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `TIME_RODADA` ADD CONSTRAINT `TIME_RODADA_TIME_ID_fkey` FOREIGN KEY (`TIME_ID`) REFERENCES `TIME_CARTOLA`(`TIME_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `SUBSTITUICAO_TIME_RODADA` ADD CONSTRAINT `SUBSTITUICAO_TIME_RODADA_TIME_RODADA_ID_fkey` FOREIGN KEY (`TIME_RODADA_ID`) REFERENCES `TIME_RODADA`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `PONTUACAO_TIME_RODADA` ADD CONSTRAINT `PONTUACAO_TIME_RODADA_TIME_RODADA_ID_fkey` FOREIGN KEY (`TIME_RODADA_ID`) REFERENCES `TIME_RODADA`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ESCALACAO_TIME_RODADA` ADD CONSTRAINT `ESCALACAO_TIME_RODADA_TIME_RODADA_ID_fkey` FOREIGN KEY (`TIME_RODADA_ID`) REFERENCES `TIME_RODADA`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `AUTH_ACCOUNT` ADD CONSTRAINT `AUTH_ACCOUNT_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `USUARIO`(`id_usuario`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `PASSWORD_RESET_TOKEN` ADD CONSTRAINT `PASSWORD_RESET_TOKEN_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `USUARIO`(`id_usuario`) ON DELETE CASCADE ON UPDATE CASCADE;
