CREATE TABLE `PONTUACAO_TIME_RODADA` (
    `ID` VARCHAR(36) NOT NULL,
    `TIME_RODADA_ID` VARCHAR(36) NOT NULL,
    `PONTUACAO` DECIMAL(12, 2) NOT NULL,
    `STATUS` ENUM('PARCIAL', 'FINAL') NOT NULL DEFAULT 'PARCIAL',
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    UNIQUE INDEX `PONTUACAO_TIME_RODADA_TIME_RODADA_ID_key` (`TIME_RODADA_ID`),
    PRIMARY KEY (`ID`),
    CONSTRAINT `PONTUACAO_TIME_RODADA_TIME_RODADA_ID_fkey`
      FOREIGN KEY (`TIME_RODADA_ID`) REFERENCES `TIME_RODADA`(`ID`)
      ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
