-- CreateTable
CREATE TABLE `DESAFIO` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(255) NOT NULL,
    `DESCRICAO` TEXT NULL,
    `TIPO_ACESSO` ENUM('FREE', 'PAGO') NOT NULL DEFAULT 'FREE',
    `VALOR_INSCRICAO` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `STATUS` ENUM('RASCUNHO', 'ABERTO', 'EM_ANDAMENTO', 'ENCERRADO', 'CANCELADO') NOT NULL DEFAULT 'RASCUNHO',
    `INICIO_INSCRICAO` DATETIME(3) NOT NULL,
    `FIM_INSCRICAO` DATETIME(3) NOT NULL,
    `DATA_INICIO` DATETIME(3) NOT NULL,
    `DATA_FIM` DATETIME(3) NOT NULL,
    `LIMITE_PARTICIPANTES` INTEGER UNSIGNED NULL,
    `CRIADO_POR_ID` INTEGER UNSIGNED NOT NULL,
    `PUBLICADO_EM` DATETIME(3) NULL,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    INDEX `DESAFIO_CRIADO_POR_ID_idx`(`CRIADO_POR_ID`),
    INDEX `DESAFIO_STATUS_DATA_INICIO_idx`(`STATUS`, `DATA_INICIO`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DESAFIO_PARTIDA` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `DESAFIO_ID` INTEGER UNSIGNED NOT NULL,
    `FIXTURE_ID_API_FOOTBALL` INTEGER UNSIGNED NOT NULL,
    `LEAGUE_ID_API_FOOTBALL` INTEGER UNSIGNED NOT NULL,
    `NOME_COMPETICAO` VARCHAR(255) NOT NULL,
    `MANDANTE_ID_API_FOOTBALL` INTEGER UNSIGNED NOT NULL,
    `NOME_MANDANTE` VARCHAR(255) NOT NULL,
    `LOGO_MANDANTE_URL` TEXT NULL,
    `VISITANTE_ID_API_FOOTBALL` INTEGER UNSIGNED NOT NULL,
    `NOME_VISITANTE` VARCHAR(255) NOT NULL,
    `LOGO_VISITANTE_URL` TEXT NULL,
    `DATA_INICIO` DATETIME(3) NOT NULL,
    `STATUS` ENUM('AGENDADA', 'EM_ANDAMENTO', 'FINALIZADA', 'ANULADA') NOT NULL DEFAULT 'AGENDADA',
    `RESULTADO` ENUM('CASA', 'EMPATE', 'FORA') NULL,
    `GOLS_MANDANTE` SMALLINT UNSIGNED NULL,
    `GOLS_VISITANTE` SMALLINT UNSIGNED NULL,
    `ORDEM` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    INDEX `DESAFIO_PARTIDA_DESAFIO_ID_ORDEM_idx`(`DESAFIO_ID`, `ORDEM`),
    UNIQUE INDEX `DESAFIO_PARTIDA_DESAFIO_ID_FIXTURE_ID_API_FOOTBALL_key`(`DESAFIO_ID`, `FIXTURE_ID_API_FOOTBALL`),
    UNIQUE INDEX `DESAFIO_PARTIDA_ID_DESAFIO_ID_key`(`ID`, `DESAFIO_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DESAFIO_PALPITE` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `DESAFIO_ID` INTEGER UNSIGNED NOT NULL,
    `DESAFIO_PARTIDA_ID` INTEGER UNSIGNED NOT NULL,
    `USUARIO_ID` INTEGER UNSIGNED NOT NULL,
    `PALPITE` ENUM('CASA', 'EMPATE', 'FORA') NOT NULL,
    `PONTOS` DECIMAL(12, 2) NULL,
    `APURADO` BOOLEAN NOT NULL DEFAULT false,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    INDEX `DESAFIO_PALPITE_DESAFIO_PARTIDA_ID_DESAFIO_ID_idx`(`DESAFIO_PARTIDA_ID`, `DESAFIO_ID`),
    INDEX `DESAFIO_PALPITE_DESAFIO_ID_APURADO_idx`(`DESAFIO_ID`, `APURADO`),
    INDEX `DESAFIO_PALPITE_USUARIO_ID_DESAFIO_ID_idx`(`USUARIO_ID`, `DESAFIO_ID`),
    UNIQUE INDEX `DESAFIO_PALPITE_DESAFIO_PARTIDA_ID_USUARIO_ID_key`(`DESAFIO_PARTIDA_ID`, `USUARIO_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DESAFIO_INSCRICAO` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `DESAFIO_ID` INTEGER UNSIGNED NOT NULL,
    `USUARIO_ID` INTEGER UNSIGNED NOT NULL,
    `STATUS` ENUM('ATIVA', 'CANCELADA') NOT NULL DEFAULT 'ATIVA',
    `VALOR_INSCRICAO` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `MOVIMENTACAO_DEBITO_ID` INTEGER UNSIGNED NULL,
    `DATA_INSCRICAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    UNIQUE INDEX `DESAFIO_INSCRICAO_MOVIMENTACAO_DEBITO_ID_key`(`MOVIMENTACAO_DEBITO_ID`),
    INDEX `DESAFIO_INSCRICAO_USUARIO_ID_idx`(`USUARIO_ID`),
    INDEX `DESAFIO_INSCRICAO_DESAFIO_ID_STATUS_idx`(`DESAFIO_ID`, `STATUS`),
    UNIQUE INDEX `DESAFIO_INSCRICAO_DESAFIO_ID_USUARIO_ID_key`(`DESAFIO_ID`, `USUARIO_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `DESAFIO` ADD CONSTRAINT `DESAFIO_CRIADO_POR_ID_fkey` FOREIGN KEY (`CRIADO_POR_ID`) REFERENCES `USUARIO`(`id_usuario`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DESAFIO_PARTIDA` ADD CONSTRAINT `DESAFIO_PARTIDA_DESAFIO_ID_fkey` FOREIGN KEY (`DESAFIO_ID`) REFERENCES `DESAFIO`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DESAFIO_PALPITE` ADD CONSTRAINT `DESAFIO_PALPITE_DESAFIO_ID_fkey` FOREIGN KEY (`DESAFIO_ID`) REFERENCES `DESAFIO`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DESAFIO_PALPITE` ADD CONSTRAINT `DESAFIO_PALPITE_DESAFIO_PARTIDA_ID_DESAFIO_ID_fkey` FOREIGN KEY (`DESAFIO_PARTIDA_ID`, `DESAFIO_ID`) REFERENCES `DESAFIO_PARTIDA`(`ID`, `DESAFIO_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `DESAFIO_PALPITE` ADD CONSTRAINT `DESAFIO_PALPITE_USUARIO_ID_fkey` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO`(`id_usuario`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DESAFIO_INSCRICAO` ADD CONSTRAINT `DESAFIO_INSCRICAO_DESAFIO_ID_fkey` FOREIGN KEY (`DESAFIO_ID`) REFERENCES `DESAFIO`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DESAFIO_INSCRICAO` ADD CONSTRAINT `DESAFIO_INSCRICAO_USUARIO_ID_fkey` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO`(`id_usuario`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DESAFIO_INSCRICAO` ADD CONSTRAINT `DESAFIO_INSCRICAO_MOVIMENTACAO_DEBITO_ID_fkey` FOREIGN KEY (`MOVIMENTACAO_DEBITO_ID`) REFERENCES `MOVIMENTACAO_CARTEIRA`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Regras estruturais complementares (CHECKs nao representados pelo Prisma).
ALTER TABLE `DESAFIO`
  ADD CONSTRAINT `DESAFIO_ACESSO_VALOR_check` CHECK (
    (`TIPO_ACESSO` = 'FREE' AND `VALOR_INSCRICAO` = 0)
    OR (`TIPO_ACESSO` = 'PAGO' AND `VALOR_INSCRICAO` > 0)
  ),
  ADD CONSTRAINT `DESAFIO_LIMITE_check` CHECK (`LIMITE_PARTICIPANTES` IS NULL OR `LIMITE_PARTICIPANTES` > 0);

ALTER TABLE `DESAFIO_INSCRICAO`
  ADD CONSTRAINT `DESAFIO_INSCRICAO_VALOR_check` CHECK (`VALOR_INSCRICAO` >= 0);
