-- CreateTable
CREATE TABLE `LIGA` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(255) NOT NULL,
    `SLUG` VARCHAR(255) NOT NULL,
    `DESCRICAO` TEXT NULL,
    `IMAGEM_URL` TEXT NULL,
    `TIPO` ENUM('OFICIAL', 'PRIVADA') NOT NULL,
    `STATUS` ENUM('ATIVA', 'INATIVA') NOT NULL DEFAULT 'ATIVA',
    `VISIVEL_APP` BOOLEAN NOT NULL DEFAULT true,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    UNIQUE INDEX `LIGA_SLUG_key`(`SLUG`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MODALIDADE_COMPETICAO` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `CODIGO` VARCHAR(50) NOT NULL,
    `NOME` VARCHAR(255) NOT NULL,
    `DESCRICAO` TEXT NULL,
    `ATIVA` BOOLEAN NOT NULL DEFAULT true,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    UNIQUE INDEX `MODALIDADE_COMPETICAO_CODIGO_key`(`CODIGO`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LIGA_MODALIDADE` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `LIGA_ID` INTEGER UNSIGNED NOT NULL,
    `MODALIDADE_ID` INTEGER UNSIGNED NOT NULL,
    `ATIVA` BOOLEAN NOT NULL DEFAULT true,
    `ORDEM` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    INDEX `LIGA_MODALIDADE_MODALIDADE_ID_idx`(`MODALIDADE_ID`),
    UNIQUE INDEX `LIGA_MODALIDADE_LIGA_ID_MODALIDADE_ID_key`(`LIGA_ID`, `MODALIDADE_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COMPETICAO_LIGA` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `LIGA_MODALIDADE_ID` INTEGER UNSIGNED NOT NULL,
    `NOME` VARCHAR(255) NOT NULL,
    `SLUG` VARCHAR(255) NOT NULL,
    `DESCRICAO` TEXT NULL,
    `TIPO_ACESSO` ENUM('FREE', 'PAGO') NOT NULL DEFAULT 'FREE',
    `VALOR_INSCRICAO` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `TIPO_TAXA_PLATAFORMA` ENUM('PERCENTUAL', 'VALOR_FIXO') NULL,
    `VALOR_TAXA_PLATAFORMA` DECIMAL(12, 2) NULL,
    `RODADA_INICIO` TINYINT UNSIGNED NULL,
    `RODADA_FIM` TINYINT UNSIGNED NULL,
    `DATA_INICIO` DATETIME(3) NULL,
    `DATA_FIM` DATETIME(3) NULL,
    `INICIO_INSCRICAO` DATETIME(3) NULL,
    `FIM_INSCRICAO` DATETIME(3) NULL,
    `LIMITE_TIMES_USUARIO` INTEGER UNSIGNED NULL,
    `LIMITE_PARTICIPANTES` INTEGER UNSIGNED NULL,
    `STATUS` ENUM('RASCUNHO', 'INSCRICOES_ABERTAS', 'INSCRICOES_ENCERRADAS', 'EM_ANDAMENTO', 'ENCERRADA', 'CANCELADA') NOT NULL DEFAULT 'RASCUNHO',
    `VISIVEL_APP` BOOLEAN NOT NULL DEFAULT false,
    `DESTAQUE` BOOLEAN NOT NULL DEFAULT false,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    UNIQUE INDEX `COMPETICAO_LIGA_SLUG_key`(`SLUG`),
    INDEX `COMPETICAO_LIGA_LIGA_MODALIDADE_ID_STATUS_VISIVEL_APP_idx`(`LIGA_MODALIDADE_ID`, `STATUS`, `VISIVEL_APP`),
    INDEX `COMPETICAO_LIGA_RODADA_INICIO_idx`(`RODADA_INICIO`),
    INDEX `COMPETICAO_LIGA_STATUS_VISIVEL_APP_idx`(`STATUS`, `VISIVEL_APP`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PREMIACAO_COMPETICAO` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `COMPETICAO_LIGA_ID` INTEGER UNSIGNED NOT NULL,
    `POSICAO_INICIO` INTEGER UNSIGNED NOT NULL,
    `POSICAO_FIM` INTEGER UNSIGNED NOT NULL,
    `TIPO_PREMIACAO` ENUM('VALOR_FIXO', 'PERCENTUAL') NOT NULL,
    `VALOR` DECIMAL(12, 2) NULL,
    `PERCENTUAL` DECIMAL(7, 4) NULL,
    `ORDEM` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    INDEX `PREMIACAO_COMPETICAO_COMPETICAO_LIGA_ID_ORDEM_idx`(`COMPETICAO_LIGA_ID`, `ORDEM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `INSCRICAO_TIME_COMPETICAO` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `COMPETICAO_LIGA_ID` INTEGER UNSIGNED NOT NULL,
    `USUARIO_ID` INTEGER UNSIGNED NOT NULL,
    `TIME_ID_CARTOLA` INTEGER UNSIGNED NOT NULL,
    `NOME_TIME` VARCHAR(255) NOT NULL,
    `NOME_CARTOLEIRO` VARCHAR(255) NULL,
    `ESCUDO_URL` TEXT NULL,
    `VALOR_INSCRICAO` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `STATUS_INSCRICAO` ENUM('ATIVA', 'CANCELADA', 'FINALIZADA') NOT NULL DEFAULT 'ATIVA',
    `PONTUACAO` DECIMAL(12, 2) NULL,
    `POSICAO` INTEGER UNSIGNED NULL,
    `POSICAO_ANTERIOR` INTEGER UNSIGNED NULL,
    `PREMIO_APURADO` DECIMAL(12, 2) NULL,
    `DATA_INSCRICAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CANCELADA_EM` DATETIME(3) NULL,
    `FINALIZADO_EM` DATETIME(3) NULL,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    INDEX `INSCRICAO_TIME_COMPETICAO_USUARIO_ID_COMPETICAO_LIGA_ID_idx`(`USUARIO_ID`, `COMPETICAO_LIGA_ID`),
    INDEX `INSCRICAO_TIME_COMPETICAO_COMPETICAO_LIGA_ID_STATUS_INSCRICA_idx`(`COMPETICAO_LIGA_ID`, `STATUS_INSCRICAO`, `POSICAO`),
    UNIQUE INDEX `INSCRICAO_TIME_COMPETICAO_COMPETICAO_LIGA_ID_TIME_ID_CARTOLA_key`(`COMPETICAO_LIGA_ID`, `TIME_ID_CARTOLA`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `COMPETICAO_LIGA`
  ADD CONSTRAINT `COMP_LIGA_VALOR_INSCRICAO_check` CHECK (`VALOR_INSCRICAO` >= 0),
  ADD CONSTRAINT `COMP_LIGA_VALOR_TAXA_check` CHECK (`VALOR_TAXA_PLATAFORMA` IS NULL OR `VALOR_TAXA_PLATAFORMA` >= 0),
  ADD CONSTRAINT `COMP_LIGA_LIMITE_TIMES_check` CHECK (`LIMITE_TIMES_USUARIO` IS NULL OR `LIMITE_TIMES_USUARIO` > 0),
  ADD CONSTRAINT `COMP_LIGA_LIMITE_PART_check` CHECK (`LIMITE_PARTICIPANTES` IS NULL OR `LIMITE_PARTICIPANTES` > 0),
  ADD CONSTRAINT `COMP_LIGA_RODADAS_check` CHECK (`RODADA_INICIO` IS NULL OR `RODADA_FIM` IS NULL OR `RODADA_FIM` >= `RODADA_INICIO`),
  ADD CONSTRAINT `COMP_LIGA_DATAS_check` CHECK (`DATA_INICIO` IS NULL OR `DATA_FIM` IS NULL OR `DATA_FIM` >= `DATA_INICIO`),
  ADD CONSTRAINT `COMP_LIGA_INSCRICOES_check` CHECK (`INICIO_INSCRICAO` IS NULL OR `FIM_INSCRICAO` IS NULL OR `FIM_INSCRICAO` >= `INICIO_INSCRICAO`),
  ADD CONSTRAINT `COMP_LIGA_FREE_check` CHECK (`TIPO_ACESSO` <> 'FREE' OR `VALOR_INSCRICAO` = 0);

ALTER TABLE `PREMIACAO_COMPETICAO`
  ADD CONSTRAINT `PREMIACAO_POSICOES_check` CHECK (`POSICAO_INICIO` > 0 AND `POSICAO_FIM` >= `POSICAO_INICIO`),
  ADD CONSTRAINT `PREMIACAO_VALOR_check` CHECK (`VALOR` IS NULL OR `VALOR` >= 0),
  ADD CONSTRAINT `PREMIACAO_PERCENTUAL_check` CHECK (`PERCENTUAL` IS NULL OR (`PERCENTUAL` >= 0 AND `PERCENTUAL` <= 100));

ALTER TABLE `INSCRICAO_TIME_COMPETICAO`
  ADD CONSTRAINT `INSCRICAO_VALOR_check` CHECK (`VALOR_INSCRICAO` >= 0),
  ADD CONSTRAINT `INSCRICAO_POSICAO_check` CHECK (`POSICAO` IS NULL OR `POSICAO` > 0),
  ADD CONSTRAINT `INSCRICAO_POSICAO_ANT_check` CHECK (`POSICAO_ANTERIOR` IS NULL OR `POSICAO_ANTERIOR` > 0),
  ADD CONSTRAINT `INSCRICAO_PREMIO_check` CHECK (`PREMIO_APURADO` IS NULL OR `PREMIO_APURADO` >= 0);

-- AddForeignKey
ALTER TABLE `LIGA_MODALIDADE` ADD CONSTRAINT `LIGA_MODALIDADE_LIGA_ID_fkey` FOREIGN KEY (`LIGA_ID`) REFERENCES `LIGA`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `LIGA_MODALIDADE` ADD CONSTRAINT `LIGA_MODALIDADE_MODALIDADE_ID_fkey` FOREIGN KEY (`MODALIDADE_ID`) REFERENCES `MODALIDADE_COMPETICAO`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMPETICAO_LIGA` ADD CONSTRAINT `COMPETICAO_LIGA_LIGA_MODALIDADE_ID_fkey` FOREIGN KEY (`LIGA_MODALIDADE_ID`) REFERENCES `LIGA_MODALIDADE`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PREMIACAO_COMPETICAO` ADD CONSTRAINT `PREMIACAO_COMPETICAO_COMPETICAO_LIGA_ID_fkey` FOREIGN KEY (`COMPETICAO_LIGA_ID`) REFERENCES `COMPETICAO_LIGA`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INSCRICAO_TIME_COMPETICAO` ADD CONSTRAINT `INSCRICAO_TIME_COMPETICAO_COMPETICAO_LIGA_ID_fkey` FOREIGN KEY (`COMPETICAO_LIGA_ID`) REFERENCES `COMPETICAO_LIGA`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INSCRICAO_TIME_COMPETICAO` ADD CONSTRAINT `INSCRICAO_TIME_COMPETICAO_USUARIO_ID_fkey` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO`(`id_usuario`) ON DELETE RESTRICT ON UPDATE CASCADE;
