CREATE TABLE `SUBSTITUICAO_TIME_RODADA` (
    `ID` VARCHAR(36) NOT NULL,
    `TIME_RODADA_ID` VARCHAR(36) NOT NULL,
    `ATLETA_SAIU_ID` INTEGER UNSIGNED NOT NULL,
    `ATLETA_ENTROU_ID` INTEGER UNSIGNED NOT NULL,
    `POSICAO_ID` INTEGER UNSIGNED NOT NULL,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    UNIQUE INDEX `SUB_TR_PAIR_key`
      (`TIME_RODADA_ID`, `ATLETA_SAIU_ID`, `ATLETA_ENTROU_ID`),
    INDEX `SUBSTITUICAO_TIME_RODADA_ATLETA_SAIU_ID_idx` (`ATLETA_SAIU_ID`),
    INDEX `SUBSTITUICAO_TIME_RODADA_ATLETA_ENTROU_ID_idx` (`ATLETA_ENTROU_ID`),
    PRIMARY KEY (`ID`),
    CONSTRAINT `SUBSTITUICAO_TIME_RODADA_TIME_RODADA_ID_fkey`
      FOREIGN KEY (`TIME_RODADA_ID`) REFERENCES `TIME_RODADA`(`ID`)
      ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
