CREATE TABLE `TIME_USUARIO` (
    `USUARIO_ID` VARCHAR(36) NOT NULL,
    `TIME_ID` INTEGER UNSIGNED NOT NULL,
    `NOME` VARCHAR(255) NOT NULL,
    `NOME_CARTOLA` VARCHAR(255) NULL,
    `SLUG` VARCHAR(255) NULL,
    `URL_ESCUDO_PNG` TEXT NULL,
    `FOTO_PERFIL` TEXT NULL,
    `ASSINANTE` BOOLEAN NULL,
    `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ATUALIZADO_EM` DATETIME(3) NOT NULL,

    INDEX `TIME_USUARIO_TIME_ID_idx`(`TIME_ID`),
    PRIMARY KEY (`USUARIO_ID`, `TIME_ID`),
    CONSTRAINT `TIME_USUARIO_USUARIO_ID_fkey`
      FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO`(`id_usuario`)
      ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
