-- Carga inicial do piloto FREE. Reexecucoes preservam registros existentes.
-- Datas fixas de teste para a temporada 2026 (nao dependem de NOW()).
START TRANSACTION;

INSERT INTO `LIGA` (`NOME`, `SLUG`, `TIPO`, `STATUS`, `VISIVEL_APP`, `CRIADO_EM`, `ATUALIZADO_EM`)
VALUES ('POINT FFC', 'point-ffc', 'OFICIAL', 'ATIVA', TRUE, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3))
ON DUPLICATE KEY UPDATE `ID` = `ID`;

INSERT INTO `MODALIDADE_COMPETICAO` (`CODIGO`, `NOME`, `ATIVA`, `CRIADO_EM`, `ATUALIZADO_EM`)
VALUES ('RODADA', 'Rodada', TRUE, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3))
ON DUPLICATE KEY UPDATE `ID` = `ID`;

INSERT INTO `LIGA_MODALIDADE` (`LIGA_ID`, `MODALIDADE_ID`, `ATIVA`, `ORDEM`, `CRIADO_EM`, `ATUALIZADO_EM`)
SELECT l.`ID`, m.`ID`, TRUE, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
FROM `LIGA` AS l
JOIN `MODALIDADE_COMPETICAO` AS m ON m.`CODIGO` = 'RODADA'
WHERE l.`SLUG` = 'point-ffc'
ON DUPLICATE KEY UPDATE `ORDEM` = `ORDEM`;

INSERT INTO `COMPETICAO_LIGA` (
  `LIGA_MODALIDADE_ID`, `NOME`, `SLUG`, `TIPO_ACESSO`, `VALOR_INSCRICAO`,
  `TIPO_TAXA_PLATAFORMA`, `VALOR_TAXA_PLATAFORMA`,
  `RODADA_INICIO`, `RODADA_FIM`, `DATA_INICIO`, `DATA_FIM`,
  `INICIO_INSCRICAO`, `FIM_INSCRICAO`, `LIMITE_TIMES_USUARIO`, `LIMITE_PARTICIPANTES`,
  `STATUS`, `VISIVEL_APP`, `DESTAQUE`, `CRIADO_EM`, `ATUALIZADO_EM`
)
SELECT lm.`ID`, 'POINT FFC - Rodada 27', 'point-ffc-rodada-27', 'FREE', 0.00,
  NULL, NULL,
  27, 27, '2026-10-01 00:00:00', '2026-10-07 23:59:59',
  '2026-09-01 00:00:00', '2026-09-30 23:59:59', 30, NULL,
  'INSCRICOES_ABERTAS', TRUE, TRUE, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
FROM `LIGA_MODALIDADE` AS lm
JOIN `LIGA` AS l ON l.`ID` = lm.`LIGA_ID` AND l.`SLUG` = 'point-ffc'
JOIN `MODALIDADE_COMPETICAO` AS m ON m.`ID` = lm.`MODALIDADE_ID` AND m.`CODIGO` = 'RODADA'
ON DUPLICATE KEY UPDATE `TIPO_ACESSO` = `TIPO_ACESSO`;

-- Sem premiacao financeira e sem inscricoes automaticas.
COMMIT;
