ALTER TABLE `MOVIMENTACAO_CARTEIRA`
  ADD COLUMN `recargaId` INTEGER UNSIGNED NULL,
  ADD UNIQUE INDEX `MOVIMENTACAO_CARTEIRA_recargaId_key` (`recargaId`),
  ADD CONSTRAINT `MOVIMENTACAO_CARTEIRA_recargaId_fkey`
    FOREIGN KEY (`recargaId`) REFERENCES `RECARGA_CARTEIRA` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE;
