-- Executar com escritores de Desafios suspensos: DDL MySQL faz commit implicito.
-- Nenhuma tabela/linha existente e apagada; os IDs e snapshots financeiros sao mantidos.
ALTER TABLE `DESAFIO`
  ADD COLUMN `LIMITE_INSCRICOES_POR_USUARIO` INTEGER UNSIGNED NOT NULL DEFAULT 1,
  ADD CONSTRAINT `DESAFIO_LIMITE_USUARIO_check` CHECK (`LIMITE_INSCRICOES_POR_USUARIO` > 0);

ALTER TABLE `DESAFIO_INSCRICAO`
  MODIFY COLUMN `STATUS` ENUM('RASCUNHO', 'ATIVA', 'CANCELADA') NOT NULL DEFAULT 'ATIVA',
  ADD COLUMN `SEQUENCIA` INTEGER UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN `CHAVE_IDEMPOTENCIA` VARCHAR(100) NULL,
  ADD UNIQUE INDEX `DESAFIO_INSCRICAO_DESAFIO_ID_USUARIO_ID_SEQUENCIA_key` (`DESAFIO_ID`, `USUARIO_ID`, `SEQUENCIA`),
  ADD UNIQUE INDEX `DESAFIO_INSCRICAO_DESAFIO_ID_USUARIO_ID_CHAVE_IDEMPOTENCIA_key` (`DESAFIO_ID`, `USUARIO_ID`, `CHAVE_IDEMPOTENCIA`),
  ADD UNIQUE INDEX `DESAFIO_INSCRICAO_ID_DESAFIO_ID_USUARIO_ID_key` (`ID`, `DESAFIO_ID`, `USUARIO_ID`),
  ADD CONSTRAINT `DESAFIO_INSCRICAO_SEQUENCIA_check` CHECK (`SEQUENCIA` > 0);

ALTER TABLE `DESAFIO_PALPITE` ADD COLUMN `INSCRICAO_ID` INTEGER UNSIGNED NULL;

-- O fluxo legado permite palpitar antes de efetivar. Preserva esses palpites em
-- rascunhos sem cobrar nem criar participacao ativa. Inscricoes atuais ficam intactas.
INSERT INTO `DESAFIO_INSCRICAO`
  (`DESAFIO_ID`, `USUARIO_ID`, `STATUS`, `SEQUENCIA`, `VALOR_INSCRICAO`, `DATA_INSCRICAO`, `CRIADO_EM`, `ATUALIZADO_EM`)
SELECT p.`DESAFIO_ID`, p.`USUARIO_ID`, 'RASCUNHO', 1, 0,
  MIN(p.`CRIADO_EM`), MIN(p.`CRIADO_EM`), MAX(p.`ATUALIZADO_EM`)
FROM `DESAFIO_PALPITE` p
LEFT JOIN `DESAFIO_INSCRICAO` i ON i.`DESAFIO_ID` = p.`DESAFIO_ID` AND i.`USUARIO_ID` = p.`USUARIO_ID`
WHERE i.`ID` IS NULL
GROUP BY p.`DESAFIO_ID`, p.`USUARIO_ID`;

UPDATE `DESAFIO_PALPITE` p
JOIN `DESAFIO_INSCRICAO` i ON i.`DESAFIO_ID` = p.`DESAFIO_ID` AND i.`USUARIO_ID` = p.`USUARIO_ID` AND i.`SEQUENCIA` = 1
SET p.`INSCRICAO_ID` = i.`ID`;

-- NOT NULL e FK interrompem a migration se algum palpite nao puder ser vinculado.
ALTER TABLE `DESAFIO_PALPITE`
  MODIFY COLUMN `INSCRICAO_ID` INTEGER UNSIGNED NOT NULL,
  ADD UNIQUE INDEX `DESAFIO_PALPITE_INSCRICAO_ID_DESAFIO_PARTIDA_ID_key` (`INSCRICAO_ID`, `DESAFIO_PARTIDA_ID`),
  ADD INDEX `DESAFIO_PALPITE_INSCRICAO_ID_DESAFIO_ID_USUARIO_ID_idx` (`INSCRICAO_ID`, `DESAFIO_ID`, `USUARIO_ID`),
  ADD CONSTRAINT `DESAFIO_PALPITE_INSCRICAO_ID_DESAFIO_ID_USUARIO_ID_fkey`
    FOREIGN KEY (`INSCRICAO_ID`, `DESAFIO_ID`, `USUARIO_ID`)
    REFERENCES `DESAFIO_INSCRICAO` (`ID`, `DESAFIO_ID`, `USUARIO_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  DROP INDEX `DESAFIO_PALPITE_DESAFIO_PARTIDA_ID_USUARIO_ID_key`;

ALTER TABLE `DESAFIO_INSCRICAO` DROP INDEX `DESAFIO_INSCRICAO_DESAFIO_ID_USUARIO_ID_key`;
