-- Aditiva: nao cria lotes nem vinculos financeiros para inscricoes historicas.
CREATE TABLE `LOTE_INSCRICAO` (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` INTEGER UNSIGNED NOT NULL,
  `COMPETICAO_LIGA_ID` INTEGER UNSIGNED NOT NULL,
  `CHAVE_IDEMPOTENCIA_HASH` CHAR(64) NOT NULL,
  `REQUEST_HASH` CHAR(64) NOT NULL,
  `TIPO_ACESSO` ENUM('FREE', 'PAGO') NOT NULL,
  `QUANTIDADE` INTEGER UNSIGNED NOT NULL,
  `VALOR_UNITARIO` DECIMAL(12,2) NOT NULL,
  `VALOR_TOTAL` DECIMAL(12,2) NOT NULL,
  `MOEDA` CHAR(3) NOT NULL DEFAULT 'BRL',
  `MOVIMENTACAO_DEBITO_ID` INTEGER UNSIGNED NULL,
  `RESPOSTA_ORIGINAL` JSON NULL,
  `CONFIRMADO_EM` DATETIME(3) NULL,
  `CRIADO_EM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `ATUALIZADO_EM` DATETIME(3) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `LOTE_INSCRICAO_USUARIO_CHAVE_key` (`USUARIO_ID`, `CHAVE_IDEMPOTENCIA_HASH`),
  UNIQUE INDEX `LOTE_INSCRICAO_DEBITO_key` (`MOVIMENTACAO_DEBITO_ID`),
  INDEX `LOTE_INSCRICAO_COMPETICAO_CONFIRMACAO_idx` (`COMPETICAO_LIGA_ID`, `CONFIRMADO_EM`),
  CONSTRAINT `LOTE_INSCRICAO_USUARIO_fkey` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO` (`id_usuario`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `LOTE_INSCRICAO_COMPETICAO_fkey` FOREIGN KEY (`COMPETICAO_LIGA_ID`) REFERENCES `COMPETICAO_LIGA` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `LOTE_INSCRICAO_DEBITO_fkey` FOREIGN KEY (`MOVIMENTACAO_DEBITO_ID`) REFERENCES `MOVIMENTACAO_CARTEIRA` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `LOTE_INSCRICAO_QUANTIDADE_check` CHECK (`QUANTIDADE` > 0),
  CONSTRAINT `LOTE_INSCRICAO_VALORES_check` CHECK (`VALOR_UNITARIO` >= 0 AND `VALOR_TOTAL` = `VALOR_UNITARIO` * `QUANTIDADE`),
  CONSTRAINT `LOTE_INSCRICAO_ACESSO_check` CHECK (
    (`TIPO_ACESSO` = 'FREE' AND `VALOR_TOTAL` = 0 AND `MOVIMENTACAO_DEBITO_ID` IS NULL)
    OR (`TIPO_ACESSO` = 'PAGO' AND `VALOR_UNITARIO` > 0)
  ),
  CONSTRAINT `LOTE_INSCRICAO_CONFIRMACAO_check` CHECK (
    `TIPO_ACESSO` <> 'PAGO' OR `CONFIRMADO_EM` IS NULL OR `MOVIMENTACAO_DEBITO_ID` IS NOT NULL
  )
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `INSCRICAO_TIME_COMPETICAO`
  ADD COLUMN `LOTE_INSCRICAO_ID` INTEGER UNSIGNED NULL,
  ADD INDEX `INSCRICAO_LOTE_idx` (`LOTE_INSCRICAO_ID`),
  ADD CONSTRAINT `INSCRICAO_LOTE_fkey` FOREIGN KEY (`LOTE_INSCRICAO_ID`)
    REFERENCES `LOTE_INSCRICAO` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
