-- Additive only: no historical data is removed or marked consolidated.
CREATE TABLE `RODADA_PROCESSAMENTO` (
  `temporada` SMALLINT UNSIGNED NOT NULL,
  `rodada` TINYINT UNSIGNED NOT NULL,
  `status` ENUM('AGUARDANDO_ESCALACOES','ESCALACOES_CARREGADAS','EM_ANDAMENTO','AGUARDANDO_CONSOLIDACAO','CONSOLIDADA') NOT NULL DEFAULT 'AGUARDANDO_ESCALACOES',
  `timesPrevistos` JSON NOT NULL,
  `falhasSnapshot` JSON NOT NULL,
  `pontuados` JSON NULL,
  `partidas` JSON NULL,
  `erro` TEXT NULL,
  `lockToken` VARCHAR(36) NULL,
  `lockAte` DATETIME(3) NULL,
  `consolidadoEm` DATETIME(3) NULL,
  `atualizadoEm` DATETIME(3) NOT NULL,
  PRIMARY KEY (`temporada`, `rodada`),
  INDEX `RODADA_PROCESSAMENTO_status_temporada_rodada_idx` (`status`, `temporada`, `rodada`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `ESCALACAO_TIME_RODADA`
  ADD COLUMN `ORDEM` TINYINT UNSIGNED NULL,
  ADD COLUMN `PRECO` DECIMAL(12,2) NULL,
  ADD COLUMN `NOME` VARCHAR(255) NULL,
  ADD INDEX `ESCALACAO_TIME_RODADA_CLUBE_ID_TIME_RODADA_ID_idx` (`CLUBE_ID`, `TIME_RODADA_ID`);
ALTER TABLE `SUBSTITUICAO_TIME_RODADA` ADD COLUMN `ATIVA` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `PONTUACAO_TIME_RODADA` ADD COLUMN `CONSOLIDADO_EM` DATETIME(3) NULL;
